model = "models/full-zome.model"
framesPerSecond = 40

[simulator]
port = 3000

[[outputs]]
type = "e131"
# Have to use IP addresses here, not hostnames, because if we don't,
# a bug somewhere causes a DNS lookup for each and every e131 packet sent.
# This works as a workaround
# XXX fix it correctly
host = "192.168.100.50"
#host = "127.0.0.1"
channels = "rgb"
